### PR TITLE
Add several functions to provide republishing of Collections containing published Modules

### PR DESCRIPTION
**Pull request by pumazi**
This PR is only to add the functions for enabling the republication of Collections containing shared Modules. A followup pull request will integrate this work into the current litezip publishing procedure.

The logic is split between two packages publishing and legacy_publishing, where the publishing package contains code that is reusable outside of the legacy publishing use-cases.

Some known-issues that I'll create github issues for later:

The collection could have trees.latest = false, which would designate this collection as opting out of republication. (This "don't revision my book" feature isn't currently in use.)
The collection could have shared modules but all of them have trees.latest = false, which would indicate the collection should not be republished. At this time this would republish the exact same collection. (This "pinned version of a page" feature isn't currently in use.)
Sub-collections do not republish as part of this implementation. (It's unclear at the moment what should happen with sub-collections, because this feature is relatively new.)

Depends on Connexions/cnx-db#121
Addresses #53

### CODE REVIEW

**Comment by reedstrm** [comment]
Doing  a deeper review now, but a bit concerned by the comment about subcollections - the existing trigger function handles them correctly, if a bit laboriously, by treating them as a type of collection, that doesn't need its tree rebuilt (it will rebuild w/ the parent collection)

**Comment by reedstrm** [comment]
o.k. with this, as long as the plan is to add subcollection support ASAP.

**Comment by pumazi** [comment]
I don't really have a response to the subcollection support concern. As I've noted:
> It's unclear at the moment what should happen with sub-collections, because this feature is relatively new.

What's the expected behavior here?

Let's take the scenario of:
```
book
├── chap-a
│   ├── p-1
│   └── p-2
├── chap-b
│   ├── p-3
│   └── p-4
└── chap-c
    ├── p-5
    └── p-6
```

Let's say ``p-3`` was published as part of the overarching publication (aka contextual publication). We'd now like to republish this book containing ``p-3``. What happens?

1. ``chap-b``'s collection entry get a minor version bump. The book's tree is updated with this revision. ``book`` is not changed.
2. ``chap-b`` and ``book`` collections entries get a minor version bump. The book's tree is updated to reflect the entry changes.

The implementation at the moment ignores subcollections. What you'd like, if I understand correctly, is for the subcollection to get a revision as well. But maybe you'd like more than just that?

**Comment by pumazi** [comment]
I'm closing this due to the wishes to have sub-collections republish as the shredding does.

I'll be abandoning portions of this now since I think the top down query isn't the best approach.

**Pull request closed without merging**
