### PR TITLE
Preemptively check credentials

### PR DESCRIPTION
**Pull request by BryanEliDimas**
Resolves issue https://github.com/Connexions/nebuchadnezzar/issues/84

### CODE REVIEW

**Comment by BryanEliDimas** [comment]
@reedstrm Added a changelog entry.

**Comment by reedstrm** [comment]
Actually, just trolled through cnx-deploy - the `/ping` `/auth-ping` and `/publish-ping` routes are not available  via the multi-server deployments. Only routes starting `/api/`  route to the press server. Can we add `/api/` to all the ping routes?

**Comment by BryanEliDimas** [comment]
@reedstrm Prepended `/api` to `/ping` routes.

**Comment by BryanEliDimas** [comment]
@reedstrm Test now pass (thanks @pumazi)!

**Pull request merged**
