### PR TITLE
Add Celery to the project

### PR DESCRIPTION
**Pull request by pumazi**
This adds the Celery framework to the project in a pyramid friendly way.

I'm not completely sold on the implementation thus far. It's functional, but the usage is a little funky.

Addresses #114

### CODE REVIEW

**Comment by pumazi** [comment]
I'm going change the implemention so that all Celery Tasks in Press are bound functions. That is they will all have `self` in their definition (i.e. `def faux_task(self, ...):`). The bound tasks are really a requirement for us as seen in cnx-publishing; and as I'm finding while developing portions of the subscribers into tasks.

The major difficulty this works around is Pyramid's threadlocal request and registry. We sometimes do need access to the registry for settings and such. The implementation at the moment does this by passing the request as the first argument of a task. However, this is a problem when calling `faux_task.delay(a, b)` when the func spec is `faux_task(a, b)`; so then we're required to add a task option for `@task(typing=False)` to prevent argument type checking. All this leads to a bit of a mess...

I'm hoping that by making all tasks bound, we can simply access the Pyramid request and registry through the `Task` instance (i.e. `self.request`).

**Comment by pumazi** [comment]
Latest changes make this a simple implementation that doesn't do anything fancy. The task usage is going to be a bit funky at first, but we'll refactor that as we go.

**Comment by reedstrm** [comment]
Trying to run the tests locally, to see how this all works, and I get:
```
__________________ ERROR collecting tests/unit/test_tasks.py ___________________
ImportError while importing test module '/app/tests/unit/test_tasks.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/test_tasks.py:5: in <module>
    from celery import Celery
E   ModuleNotFoundError: No module named 'celery'
```
I have celery installed in the local virtualenv, but obviously the tests don't use that environment, they use something inside a container. I'd run locally, but … no instructions (yes, I checked readthedocs)

**Comment by reedstrm** [comment]
rebuilding docker containers seems to have solved it. Seems to me that some `make` magic with timestamp files in the `.state` folder should handle this sort of thing. Moving on.

**Pull request merged**
